### ISSUE TITLE
Reorganize image and sound file locations to clean up project

### ISSUE THREAD

**Issue by redbullx310** [JABeal/Fun-With-Pygame#1]
You can organize the image and sound files to separate folder locations, like /images and /sounds folders. 

To do this, create two folders in the Fun-With-Pygame folder, named images and sounds. Then, move all image files (.gif, .png, etc.) to the images folder, and all the sound files (.wav, .mp3, etc.) to the sounds folder. 

After moving all the files to the new folders, throughout the code you need to point the code to the new location of the files. For example, in Dino_Dodge.py, to point the background image to the new location of the dino_dodge_intro_background.jpg file, change the code to this:

`setBackgroundImage("images/dino_dodge_intro_background.jpg")`  

The sound files will be similar, but will use the sounds folder name instead.

**Comment by JABeal** [comment]
Thanks for the suggestion and explanation of how to accomplish this in Github! I have created the Images and Sounds folders to store these assets and updated the code accordingly.
